config/routes.rb
Rails.application.routes.draw do

	devise_for :users, controllers: { sessions: 'users/sessions' }


	#resources :pages do
	#	get "*page" => "pages#show"
	#end
  resources :posts do#, :path => 'post'
    resources :comments
  end

	resources :dashboard, :only => [:index]
	
	resources :myprofile, :only => [:index, :show]

	resources :groups, :only => [:index]

	resources :friendships

  resources :friend_feeds

	resources :tags, :only => [:index, :show]

	
	get "/pages/*page" => "pages#show"

  root "dashboard#index"

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  include Filterable # located in ./concerns/filterable.rb
  require 'action_view'
  include ActionView::Helpers::DateHelper

	# filter can ONLY take these parameters
  scope :starts_with, -> (word) {
    where("lower(description) like ?", "%#{word.downcase}%")
  }

  def username
    user.username
  end

  def submit_time_diff
    "#{distance_of_time_in_words(self.created_at, Time.now)}"
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    render locals: {
      comment: Comment.new
    }
  end

  def create
    comment = new_comment
    if comment.save
      respond_to do |format|
        format.html { redirect_to post_path(params[:post_id]) }
        format.js
      end
    else
      render :new, alert: "Error" # TODO does this work?
    end
  end

  private
  def new_comment
    comment = Post.find(params[:post_id]).comments.build(comment_params)
    comment.user_id = current_user.id
    comment
  end

  def comment_params
    params.require(:comment).permit(:description)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for comment, url: post_comments_path(post.id) do |f| %>
<form>
    <div class="form-group">
        <div class="form-group">
            <%= f.text_area :description, class: "form-control", rows: "3", placeholder: "Your comment" %>
        </div>
    </div>
    <div class="form-group actions">
        <%= f.submit "Send", class: "btn btn-one" %>
    </div>
</form>
<% end %>

app/views/comments/_mycomments.erb
<div class="container">
	<div class="post-comments">
	<% if current_user %>
		<% current_user.comments.order(created_at: :DESC).each do |comment| %>
		  <div class="media">
		    <div class="media-body">
		      <p> <%= link_to comment.post.name, post_path(comment.post.id)%> </p>
		      <p> <%= comment.description %> </p>
		    </div>
		  </div>
		<% end %>
	<% end %>
	</div>
</div>