config/routes.rb
Rails.application.routes.draw do

	devise_for :users, controllers: { sessions: 'users/sessions' }


	#resources :pages do
	#	get "*page" => "pages#show"
	#end
  resources :posts do#, :path => 'post'
    resources :comments
  end

	resources :dashboard, :only => [:index]
	
	resources :myprofile, :only => [:index, :show]

	resources :groups, :only => [:index]

	resources :friendships

  resources :friend_feeds

	resources :tags, :only => [:index, :show]

	
	get "/pages/*page" => "pages#show"

  root "dashboard#index"

end

app/views/sidebar/_sidebar.html.erb
<!-- Sidebar -->
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">


    <%= link_to dashboard_index_path, class: curr_page(dashboard_index_path) do %>
  	  <div class="sidebar-dashboard sidebar-container sidebar-tabs">
        <i class="fa fa-stack-overflow fa-3x" aria-hidden="true"></i>
        <h4>Dashboard</h4>
      </div>
    <% end %>

	<% if current_user %>
	  <%= link_to new_post_path, class: curr_page(new_post_path) do %>
	  	<div class="sidebar-create-post sidebar-container sidebar-tabs">
        <i class="fa fa-lightbulb-o fa-3x" aria-hidden="true"></i>
        <h4>New Post</h4>
      </div>
	  <% end %>

    <%= link_to myprofile_index_path, class: curr_page(myprofile_index_path) do %>
	  	<div class="sidebar-myprofile sidebar-container sidebar-tabs">
        <i class="fa  fa-folder-open fa-2x" aria-hidden="true"></i>
        <h4>Collection</h4>
      </div>
	  <% end %>

    <%= link_to friendships_path, class: curr_page(friendships_path) do %>
	  	<div class="sidebar-friends sidebar-container sidebar-tabs">
        <i class="fa fa-users fa-2x" aria-hidden="true"></i>
        <h4>Friends</h4>
      </div>
	  <% end %>

    <% end %>

  <%= link_to tags_path, class: curr_page(tags_path) do %>
  	<div class="sidebar-tags sidebar-container sidebar-tabs">
      <i class="fa fa-tags fa-2x" aria-hidden="true"></i>
      <h4>Tags</h4>
    </div>
  <% end %>

  </ul>

</div>
<!-- /#sidebar-wrapper -->