config/routes.rb
Rails.application.routes.draw do

	devise_for :users, controllers: { sessions: 'users/sessions' }


	#resources :pages do
	#	get "*page" => "pages#show"
	#end
  resources :posts do#, :path => 'post'
    resources :comments
  end

	resources :dashboard, :only => [:index]
	
	resources :myprofile, :only => [:index, :show]

	resources :groups, :only => [:index]

	resources :friendships

  resources :friend_feeds

	resources :tags, :only => [:index, :show]

	
	get "/pages/*page" => "pages#show"

  root "dashboard#index"

end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"

  def sender
    User.find(self.user_id)
  end

  def accepter
    User.find(self.friend_id)
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def index
	location = params[:location] ? params[:location] : "friendfeed"

	feed = []
	users = []
	notifs = []
	friends = []
	if location == "findusers"
		users = current_user.strangers.filter(params.slice(:starts_with))
			.paginate(page: params[:page], per_page: 50)
	elsif location == "notifications"
		notifs = current_user.pending_requests
			.paginate(page: params[:page], per_page: 50)
	elsif location == "friends"
		friends = User.where(id: current_user.friends.map(&:id))
			.filter(params.slice(:starts_with))
			.paginate(page: params[:page], per_page: 50)
	else
		location = "friendfeed"
	    feed = current_user.friend_feed
	    feed = friend_feed.where(friend_id: params[:friend_id]) if params[:friend_id].present?
	    feed = feed.order("created_at DESC")
			.paginate(page: params[:page], per_page: 50)
	end

    render locals: {
      feed: feed,
	  users: users,
	  notifications: notifs,
	  friends: friends,
      location: location
    }
  end




  def create
		friendship = current_user.friendships.build(friend_id: params[:friend_id])
		if friendship.save
			flash[:notice] = "Friend requested."
			redirect_to :back
		else
			flash[:error] = "Unable to request friendship."
			redirect_to :back
		end
  end

  def update
		friendship = Friendship.find_by(id: params[:id])
    friendship.update(accepted: true)
		if friendship.save
			redirect_to root_url, notice: "Successfully confirmed friend!"
		else
			redirect_to root_url, notice: "Sorry! Could not confirm friend!"
		end
  end

  def destroy
		Friendship.find_by(id: params[:id]).destroy
		flash[:notice] = "Removed friendship."
		redirect_to :back
  end

end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_findusers.html.erb
<h1 class="page-header">Suggested friends</h1>
<div class="well">
<ul>
<% users.each do |user| %>
    <%= link_to ' ', friendships_path(friend_id: user), :class => 'fa fa-user-plus fa-2x pull-left',  method: :post %>
    <p> <%= link_to user.username, myprofile_path(user.id) %> </p>
<% end %>
</ul>
</div>

<div id="infinite-scrolling">
  <%= will_paginate users %>
</div>

app/views/friendships/_friendfeed.html.erb
<div class="content-tab" id="content-tab">
<% feed.each do |shared| %>

    <div class="card tab-item" id="post-<%=shared.post.id%>">
    	<div class="card-img-top">

        <div class="overlay">
          <div class="media card-delete">
            <%= link_to post_path(shared.post) do %>
                <span class="glyphicon glyphicon-eye-open pull-left"></span>
            <% end %>
          </div>
          <div class="text">
            <%= shared.post.description %>
          </div>
        </div>

    		<div class="card-img-container">
    			<%= link_to image_tag(shared.post.thumbnail_image), post_path(shared.post), :class => "card-img"%>
    		</div>
    	</div>
    	<div class="card-block">
    		<h4 class="card-title">
    			<%= link_to shared.post.name, post_path(shared.post)%>
    		</h4>

    		<p class="card-text">
    			<%= shared.post.star_rating %>
    		</p>
    		<p class="card-text">
    			<small class="text-muted"> <%= "#{shared.post.submit_time_diff} by #{shared.post.poster}, shared by #{shared.friend_name}" %></small>
    		</p>
    	</div>
    </div>

<% end %>
</div>

<div id="infinite-scrolling">
  <%= will_paginate feed %>
</div>

app/views/friendships/_friends.html.erb
<h1 class="page-header">Friends</h1>
<div class="well">
    <ul class="nav ">
        <% friends.each do |friend| %>
        <ul>
        <%= link_to friend.username, myprofile_path(id: friend.id) %>
        </ul>
        <% end %>

    </ul>
</div>
<!--/.well -->
<div id="infinite-scrolling">
  <%= will_paginate friends %>
</div>

app/views/friendships/_notifications.html.erb
<h1 class="page-header">Friend Requests</h1>
<div class="well">
<% notifications.each do |request| %>
    <ul>
    <%= link_to request.sender.username, myprofile_path(request.sender.id) %>
    <%= link_to ' ',  friendship_path(id: request.id), :class => 'fa fa-check',  method: :put %>
    <%= link_to ' ',  friendship_path(id: request.id), :class => 'fa fa-minus-circle  ',  method: :delete %>
    </ul>
<% end %>
</div>

app/views/friendships/_tab.html.erb
<% friends.each do |friend| %>

  <% if false %>
  <% friends.posts.each do |post| %>
  <!-- This is a card partial, but rendering partials is slower than doing this -->
  <div class="card tab-item" id="post-<%=post.id%>">
    <div class="card-img-top">
      <div class="card-img-container">
        <%= link_to image_tag(post.thumbnail_image), :class => "card-img"%>
      </div>
    </div>
    <div class="card-block">
      <h4 class="card-title">
        <%= link_to post.name, post_path(post)%>
      </h4>
      <p class="card-text">
        <%= link_to "Go to Link", post.url %>
      </p>
      <p class="card-text">
        <%= post.rating %>
      </p>
      <p class="card-text">
        <small class="text-muted"> <%= post.submit_time_diff %> </small>
      </p>
    </div>
  </div>
  <!-- end card -->
  <% end %>
  <% end %>

<% end %>

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendships/destroy.html.erb
<h1>Friendships#destroy</h1>
<p>Find me in app/views/friendships/destroy.html.erb</p>

app/views/friendships/index.html.erb
<div class="btn-group btn-group-justified">
  <%= link_to "Friend Feed", friendships_path(location: "friendfeed"), class:"btn btn-primary"%>
  <%= link_to "Find Users", friendships_path(location: "findusers"), class:"btn btn-success"%>
  <%= link_to "Notifications", friendships_path(location: "notifications"), class:"btn btn-danger"%>
  <%= link_to "Friends", friendships_path(location: "friends"), class:"btn btn-warning"%>
</div>
<%= render location, feed: feed, users: users, notifications: notifications, friends: friends %>

app/views/friendships/update.html.erb
<h1>Friendships#update</h1>
<p>Find me in app/views/friendships/update.html.erb</p>