config/routes.rb
Rails.application.routes.draw do

	devise_for :users, controllers: { sessions: 'users/sessions' }


	#resources :pages do
	#	get "*page" => "pages#show"
	#end
  resources :posts do#, :path => 'post'
    resources :comments
  end

	resources :dashboard, :only => [:index]
	
	resources :myprofile, :only => [:index, :show]

	resources :groups, :only => [:index]

	resources :friendships

  resources :friend_feeds

	resources :tags, :only => [:index, :show]

	
	get "/pages/*page" => "pages#show"

  root "dashboard#index"

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_and_belongs_to_many :posts

  include Filterable

  scope :starts_with, -> (name) {
    where("lower(name) like ?", "%#{name.downcase}%")
  }

  def capital_name
    name.titleize
  end

  def image
    thumbnails = Set.new
    posts.each do |p|
      thumbnails << p.thumbnail_image
    end
    placeholder = Set.new
    placeholder << "ColoredVinylePH.png"
    i = thumbnails - placeholder
    if (i.size > 0)
      i.take(1)[0]
    else
      "ColoredVinylePH.png"
    end
  end

  def self.default_tags
    ["Music", "Movie", "TV", "Video"]
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    tags = Tag.filter(params.slice(:starts_with)).order("name ASC")
      .paginate(:page => params[:page], :per_page => 50)

    render locals: {
      tags: tags#Tag.all.limit(50)
    }
  end

  def show
    posts = Tag.find(params[:id]).posts.order("created_at DESC")
      .paginate(:page => params[:page], :per_page => 50)

    render locals: {
      posts: posts
    }
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/index.html.erb
<div class="row">

	<div class="col-lg-12">
		<h1 class="page-header">All Tags</h1>
	</div>

	<% tags.each do |tag| %>
		<div class="col-lg-3 col-md-4 col-xs-6 thumb">
			<div class="thumbnail tag-thumbnail text-center">
        <%= link_to tag_path(tag) do %>
          <%= image_tag(tag.image) %>
          <div class="caption-background">
            <div class="tag-caption">
              <p><%= tag.name %></p>
            </div>
          </div>
        <% end %>
			</div>
		</div>
	<% end %>

</div>
<div class="infinite-scrolling">
  <%= will_paginate tags %>
</div>

app/views/tags/show.html.erb
<div id="myposts" class="tab-pane fade in active">
    <div id="dashboard" class="dashboard">
    <% posts.each do |post| %>
		<!-- This is a card partial, but rendering partials is slower than doing this -->
		<div class="card tab-item" id="post-<%=post.id%>">
			<div class="card-img-top">

      <div class="overlay">
        <div class="media card-delete">
          <%= link_to post_path(post) do %>
            <span class="glyphicon glyphicon-eye-open pull-left"></span>
          <% end %>
        </div>
        <div class="text"> 
          <%= post.description %>
        </div>
      </div>

				<div class="card-img-container">
					<%= link_to image_tag(post.thumbnail_image), post_path(post), :class => "card-img"%>
				</div>
			</div>
			<div class="card-block">
				<h4 class="card-title">
					<%= link_to post.name, post_path(post)%>
				</h4>
				<% if false %>
				<p class="card-text">
					<%= post.description %>
				</p>
				<% end %>
				<p class="card-text">
					<%= post.star_rating %>
				</p>
				<p class="card-text">
					<small class="text-muted"> <%= post.submit_time_diff %> </small>
				</p>
			</div>
		</div>
		<!-- end card -->
	<% end %>
	</div>
</div>
<div class="infinite-scrolling">
  <%= will_paginate posts %>
</div>